version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nutric_bot_backend
    restart: unless-stopped
    working_dir: /backend
    env_file:
      - ./backend/.env
    environment:
      PYTHONPATH: /backend  # Устанавливаем PYTHONPATH, чтобы Python видел директории
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend  # Монтируем папку backend

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: nutric_bot_aiogram
    restart: unless-stopped
    env_file:
      - ./bot/.env
    depends_on:
      - backend
    volumes:
      - ./bot:/bot  # Монтируем папку bot
      - whisper_cache:/root/.cache/whisper

  db:
    image: postgres:13
    container_name: nutric_bot_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: nutric_bot_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: nutric_bot_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  alembic:
    build:
      context: .  # Контекст сборки — корневая папка проекта
      dockerfile: ./alembic/Dockerfile  # Dockerfile для Alembic
    container_name: nutric_bot_alembic
    restart: no
    environment:
      DATABASE_URL: postgresql+asyncpg://nutric_bot_user:secure_password@db:5432/nutric_bot_db
    depends_on:
      - db
    volumes:
      - ./alembic:/app/alembic  # Монтируем папку alembic в контейнер
      - ./backend:/app/backend  # Монтируем папку backend в контейнер
    working_dir: /app/alembic  # Рабочая директория для Alembic


volumes:
  db_data:
  whisper_cache:
